name: 提交句子
description: 提交一个新的句子
title: "[New]: Sentence"
body:
  - type: textarea
    id: sentence
    attributes:
      label: 句子
      description: 你的句子是什么，请不要在句尾加句号
    validations:
      required: true
  - type: textarea
    id: author
    attributes:
      label: 作者
      description: 这个句子是哪位角色说的
    validations:
      required: true